# Generated by Django 6.0.6 on 2026-06-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True, help_text="Укажите город", max_length=50, null=True, verbose_name="Город"
            ),
        ),
    ]
