# Generated by Django 6.0.6 on 2026-06-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграм chat_id",
                max_length=50,
                null=True,
                verbose_name="Телеграм chat_id",
            ),
        ),
    ]
